// flow
export const CHANGE_TRACKER_ACCURACY = 'CHANGE_TRACKER_ACCURACY';
export const SAVE_TRACKER_ACCURACY = 'SAVE_TRACKER_ACCURACY';
export const CHANGE_BACKGROUND_TRACKING = 'CHANGE_BACKGROUND_TRACKING';
export const SAVE_BACKGROUND_TRACKING = 'SAVE_BACKGROUND_TRACKING';
export const CHANGE_BATTERY_SAVER = 'CHANGE_BATTERY_SAVER';
export const SAVE_BATTERY_SAVER = 'SAVE_BATTERY_SAVER';
export const CHANGE_LOCATION_HISTORY = 'CHANGE_LOCATION_HISTORY';
export const SAVE_LOCATION_HISTORY = 'SAVE_LOCATION_HISTORY';

export const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';
export const SET_GPS_SENSOR_STATUS = 'SET_GPS_SENSOR_STATUS';
export const SET_GPS_SENSOR_ACCESS = 'SET_GPS_SENSOR_ACCESS';
export const SET_LOCATION_SET = 'SET_LOCATION_SET';
export const SAVE_CURRENT_LOCATION = 'SAVE_CURRENT_LOCATION';
export const SAVE_GPS_SENSOR_STATUS = 'SAVE_GPS_SENSOR_STATUS';
export const SAVE_GPS_SENSOR_ACCESS = 'SAVE_GPS_SENSOR_ACCESS';
export const SAVE_LOCATION_SET = 'SAVE_LOCATION_SET';