// flow

export const CHANGE_SHOW_LOCATION = 'CHANGE_SHOW_LOCATION';
export const SAVE_SHOW_LOCATION = 'SAVE_SHOW_LOCATION';
export const CHANGE_SHOW_RECENT_LOCATIONS = 'CHANGE_SHOW_RECENT_LOCATIONS';
export const SAVE_SHOW_RECENT_LOCATIONS = 'SAVE_SHOW_RECENT_LOCATIONS';
export const CHANGE_SHOWS_TRAFFIC = 'CHANGE_SHOWS_TRAFFIC';
export const SAVE_SHOWS_TRAFFIC = 'SAVE_SHOWS_TRAFFIC';
export const CHANGE_CACHE_MAPS = 'CHANGE_CACHE_MAPS';
export const SAVE_CACHE_MAPS = 'SAVE_CACHE_MAPS';
export const CHANGE_MAP_TYPE = 'CHANGE_MAP_TYPE';
export const SAVE_MAP_TYPE = 'SAVE_MAP_TYPE';
export const CHANGE_LITE_MODE = 'CHANGE_LITE_MODE';
export const SAVE_LITE_MODE = 'SAVE_LITE_MODE';

export const SET_MAP_REGION_TO = 'SET_MAP_REGION_TO';
export const SET_MAP_REGION = 'SET_MAP_REGION';
