// flow
export const SET_SEARCHING = 'SET_SEARCHING';
export const SET_HIDE_TOOLBAR = 'SET_HIDE_TOOLBAR';
export const SET_WEATHER_QUERY = 'SET_WEATHER_QUERY';
export const SET_SHOW_DIRECT_MESSAGES = 'SET_SHOW_DIRECT_MESSAGES';
export const SET_MAP_VIEW_REGION = 'SET_MAP_VIEW_REGION';

export const SAVE_SEARCHING = 'SAVE_SEARCHING';
export const SAVE_HIDE_TOOLBAR = 'SAVE_HIDE_TOOLBAR';
export const SAVE_WEATHER_QUERY = 'SAVE_WEATHER_QUERY';
export const SAVE_SHOW_DIRECT_MESSAGES = 'SAVE_SHOW_DIRECT_MESSAGES';
export const SAVE_MAP_VIEW_REGION = 'SAVE_MAP_VIEW_REGION';

